import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import { Refine } from "@refinedev/core";
import { DevtoolsProvider } from "@providers/devtools";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import { useNotificationProvider } from "@refinedev/antd";
import routerProvider from "@refinedev/nextjs-router";

import { customDataProvider } from "@providers/data-provider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@refinedev/antd/dist/reset.css";
import { AppIcon } from "@components/app-icon";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProviderClient } from "@providers/auth-provider/auth-provider.client";
import {
  UserOutlined,
  TeamOutlined,
  AppstoreOutlined,
  ToolOutlined,
  TagsOutlined,
  SafetyCertificateOutlined,
  ContactsOutlined,
  DashboardOutlined
} from "@ant-design/icons";
import { GiPlantRoots, GiFlowerPot } from "react-icons/gi";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <AntdRegistry>
              <ColorModeContextProvider defaultMode={defaultMode}>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={customDataProvider}
                    notificationProvider={useNotificationProvider}
                    authProvider={authProviderClient}
                    resources={[
                      {
                        name: "dashboard",
                        list: "/back",
                        meta: {
                          icon: <DashboardOutlined />,
                          label: "Dashboard"
                        },
                      },
                      {
                        name: "user-management",
                        meta: {
                          label: "User Management",
                          icon: <TeamOutlined />,
                        },
                      },
                      {
                        name: "persons",
                        list: "/back/persons",
                        create: "/back/persons/create",
                        edit: "/back/persons/edit/:id",
                        show: "/back/persons/show/:id",
                        meta: {
                          canDelete: true,
                          icon: <UserOutlined />,
                          parent: "user-management",
                        },
                      },
                      {
                        name: "contacts",
                        list: "/back/contacts",
                        create: "/back/contacts/create",
                        edit: "/back/contacts/edit/:id",
                        show: "/back/contacts/show/:id",
                        meta: {
                          canDelete: true,
                          icon: <ContactsOutlined />,
                          parent: "user-management",
                        },
                      },
                      {
                        name: "roles",
                        list: "/back/roles",
                        create: "/back/roles/create",
                        edit: "/back/roles/edit/:id",
                        show: "/back/roles/show/:id",
                        meta: {
                          canDelete: true,
                          icon: <SafetyCertificateOutlined />,
                          parent: "user-management",
                        },
                      },
                      /*                       {
                                              name: "parameter-types",
                                              list: "/back/parameter-types",
                                              create: "/back/parameter-types/create",
                                              edit: "/back/parameter-types/edit/:id",
                                              show: "/back/parameter-types/show/:id",
                                              meta: {
                                                canDelete: true,
                                                icon: <TagsOutlined />,
                                                parent: "user-management",
                                              },
                                            }, */
                      {
                        name: "object-management",
                        meta: {
                          label: "Object Management",
                          icon: <ToolOutlined />,
                        },
                      },
                      {
                        name: "plant-management",
                        meta: {
                          label: "Plant Management",
                          icon: <GiPlantRoots />,
                        },
                      },
                      {
                        name: "plant-types",
                        list: "/back/plant-types",
                        create: "/back/plant-types/create",
                        edit: "/back/plant-types/edit/:id",
                        show: "/back/plant-types/show/:id",
                        meta: {
                          canDelete: true,
                          icon: <AppstoreOutlined />,
                          parent: "plant-management",
                        },
                      },
                      {
                        name: "objects",
                        list: "/back/objects",
                        create: "/back/objects/create",
                        edit: "/back/objects/edit/:id",
                        show: "/back/objects/show/:id",
                        meta: {
                          canDelete: true,
                          icon: <ToolOutlined />,
                          parent: "object-management",
                        },
                      },
                      {
                        name: "category-types",
                        list: "/back/category-types",
                        create: "/back/category-types/create",
                        edit: "/back/category-types/edit/:id",
                        show: "/back/category-types/show/:id",
                        meta: {
                          canDelete: true,
                          icon: <TagsOutlined />,
                          parent: "object-management",
                        },
                      },
                      {
                        name: "plants",
                        list: "/back/plants",
                        create: "/back/plants/create",
                        edit: "/back/plants/edit/:id",
                        show: "/back/plants/show/:id",
                        meta: {
                          canDelete: true,
                          icon: <GiFlowerPot />,
                          parent: "plant-management",
                        },
                      },
                      {
                        name: "object-profiles",
                        list: "/back/object-profiles",
                        create: "/back/object-profiles/create",
                        edit: "/back/object-profiles/edit/:id",
                        show: "/back/object-profiles/show/:id",
                        meta: {
                          canDelete: true,
                          icon: <UserOutlined />,
                          parent: "object-management",
                        },
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "nIEltG-uCpbQS-GCuwdu",
                      title: { text: "backoffice", icon: <AppIcon /> },
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </ColorModeContextProvider>
            </AntdRegistry>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}